### PR TITLE
Login & Register

### PR DESCRIPTION
**Pull request by muxonn**
### Whole logic is placed in the `lib/features/api` directory
- `clients` and `core` are divided into two main parts - **API** (for the IoT data) and **AUTH** (user login and register)
- The main frontend module is `api_repository` and it's located in the same directory
- Models were moved to the `data` directory, soon I'll place there notifications as well

### Key features
- Login and register
- Saving session tokens when the user has logged in successfully
- Retrieving the token on autologin

### Plans for the next PR
- Show user's data in the app (it's already being loaded in the cubit, but has to be shown in the UI)
- Show IoT data (devices, sensors, sensor readings)
- Notifications is a feature to be done in the further future
- Robustness (advanced error handling, timeouts handling etc.)

There is a weird bug on the signup page - when the user .is correctly registered, the app automatically redirects him to login page. Tried to fix it, but for now - let's just fuck it

### CODE REVIEW

**Comment by Franek1703** [comment]
Rozwiązać te konflikty?

**Comment by muxonn** [comment]
> Rozwiązać te konflikty?

Już rozwiązane, można sprawdzać

**Comment by muxonn** [comment]
@Franek1703  @Mouson12  Żeby odpalić i testować, trzeba uruchomić serwer aplikacyjny poleceniem  `flask --app app_server run --host=0.0.0.0 --port=5000` oraz w razie potrzeby podmienić URL w `api_client_path ` oraz `auth_client_path`

**Comment by Franek1703** [comment]
Sprawdzę ci już rano na pbl

**Review by Franek1703 — APPROVED** [review]
Poprawiłem dwa błędy które miałem w tym endpoincie \api\user\info

**Pull request merged**
